apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-frontend
  template:
    metadata:
      labels:
        app: my-frontend
    spec:
      containers:
      - name: my-frontend
        image: moiz2701/my-node-frontend:latest
        ports:
        - containerPort: 3000
